### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by loretoparisi** [ajki/LoGAN#1]
Hello, I had a 

```sh
(venv) ip-192-168-1-103:LoGAN loretoparisi$ python change_colors_to_words.py

data
Progress: 100.00%
Format change complete.
Progress: 100.00%
Color word match complete.
Traceback (most recent call last):
  File "change_colors_to_words.py", line 202, in <module>
    word_most.append(color_word_sorted[2])
IndexError: list index out of range
(venv) ip-192-168-1-103:LoGAN loretoparisi$ python change_colors_to_words.py
```

So I have tried to fix it adding a guard on list size

```python
for img in colors.index:
        #sort according to amount of color
        color_word_sorted=[x for _,x in sorted(zip(colors['amount color'][img],colors['color word'][img]))]
        if len(color_word_sorted) > 2:
            word_least.append(color_word_sorted[0])
            word_middle.append(color_word_sorted[1])
            word_most.append(color_word_sorted[2])
            #sort according to amount of color
            color_word_compact_sorted = [x for _,x in sorted(zip(colors['amount color'][img],colors['color word compact'][img]))]
            compact_least.append(color_word_compact_sorted[0])
            compact_middle.append(color_word_compact_sorted[1])
            compact_most.append(color_word_compact_sorted[2])        
        
    colors.drop(colors.columns[[2,3]], axis=1, inplace= True )
    colors['word least'] = word_least
    colors['word middle'] = word_middle
    colors['word most'] = word_most
    colors['compact least'] = compact_least
    colors['compact middle'] = compact_middle
    colors['compact most'] = compact_most
```

problem is that now I get a wrong DataFrame size:

```sh
Progress: 100.00%
Format change complete.
Progress: 100.00%
Color word match complete.
Traceback (most recent call last):
  File "change_colors_to_words.py", line 211, in <module>
    colors['word least'] = word_least
  File "/Users/loretoparisi/Documents/Projects/AI/LoGAN/venv/lib/python3.6/site-packages/pandas/core/frame.py", line 3119, in __setitem__
    self._set_item(key, value)
  File "/Users/loretoparisi/Documents/Projects/AI/LoGAN/venv/lib/python3.6/site-packages/pandas/core/frame.py", line 3194, in _set_item
    value = self._sanitize_column(key, value)
  File "/Users/loretoparisi/Documents/Projects/AI/LoGAN/venv/lib/python3.6/site-packages/pandas/core/frame.py", line 3391, in _sanitize_column
    value = _sanitize_index(value, self.index, copy=False)
  File "/Users/loretoparisi/Documents/Projects/AI/LoGAN/venv/lib/python3.6/site-packages/pandas/core/series.py", line 4001, in _sanitize_index
    raise ValueError('Length of values does not match length of ' 'index')
ValueError: Length of values does not match length of index
```

May I have to add zero values in the `else` of that guard?

Thank you.

**Comment by kawsor** [comment]
> Hello, I had a
> 
> ```shell
> (venv) ip-192-168-1-103:LoGAN loretoparisi$ python change_colors_to_words.py
> 
> data
> Progress: 100.00%
> Format change complete.
> Progress: 100.00%
> Color word match complete.
> Traceback (most recent call last):
>   File "change_colors_to_words.py", line 202, in <module>
>     word_most.append(color_word_sorted[2])
> IndexError: list index out of range
> (venv) ip-192-168-1-103:LoGAN loretoparisi$ python change_colors_to_words.py
> ```
> 
> So I have tried to fix it adding a guard on list size
> 
> ```python
> for img in colors.index:
>         #sort according to amount of color
>         color_word_sorted=[x for _,x in sorted(zip(colors['amount color'][img],colors['color word'][img]))]
>         if len(color_word_sorted) > 2:
>             word_least.append(color_word_sorted[0])
>             word_middle.append(color_word_sorted[1])
>             word_most.append(color_word_sorted[2])
>             #sort according to amount of color
>             color_word_compact_sorted = [x for _,x in sorted(zip(colors['amount color'][img],colors['color word compact'][img]))]
>             compact_least.append(color_word_compact_sorted[0])
>             compact_middle.append(color_word_compact_sorted[1])
>             compact_most.append(color_word_compact_sorted[2])        
>         
>     colors.drop(colors.columns[[2,3]], axis=1, inplace= True )
>     colors['word least'] = word_least
>     colors['word middle'] = word_middle
>     colors['word most'] = word_most
>     colors['compact least'] = compact_least
>     colors['compact middle'] = compact_middle
>     colors['compact most'] = compact_most
> ```
> 
> problem is that now I get a wrong DataFrame size:
> 
> ```shell
> Progress: 100.00%
> Format change complete.
> Progress: 100.00%
> Color word match complete.
> Traceback (most recent call last):
>   File "change_colors_to_words.py", line 211, in <module>
>     colors['word least'] = word_least
>   File "/Users/loretoparisi/Documents/Projects/AI/LoGAN/venv/lib/python3.6/site-packages/pandas/core/frame.py", line 3119, in __setitem__
>     self._set_item(key, value)
>   File "/Users/loretoparisi/Documents/Projects/AI/LoGAN/venv/lib/python3.6/site-packages/pandas/core/frame.py", line 3194, in _set_item
>     value = self._sanitize_column(key, value)
>   File "/Users/loretoparisi/Documents/Projects/AI/LoGAN/venv/lib/python3.6/site-packages/pandas/core/frame.py", line 3391, in _sanitize_column
>     value = _sanitize_index(value, self.index, copy=False)
>   File "/Users/loretoparisi/Documents/Projects/AI/LoGAN/venv/lib/python3.6/site-packages/pandas/core/series.py", line 4001, in _sanitize_index
>     raise ValueError('Length of values does not match length of ' 'index')
> ValueError: Length of values does not match length of index
> ```
> 
> May I have to add zero values in the `else` of that guard?
> 
> Thank you.

Have you fixed it?

**Comment by loretoparisi** [comment]
@kawsor nope. Since I have put that guard the shape of the tensor now will look different here:

```python
if len(color_word_sorted) > 2:
            word_least.append(color_word_sorted[0])
```

so this may led to the error later on:

```sh
ValueError: Length of values does not match length of index
```

Not sure how to pad those values then.

**Comment by kawsor** [comment]
@loretoparisi Can you help me fix the issue I submitted, I got a faked csv file by change  word_most.append(color_word_sorted[2]  to 
word_most.append(color_word_sorted[1]
https://github.com/ajki/LoGAN/issues/2

**Comment by loretoparisi** [comment]
@kawsor so it worked in that way?

**Comment by kawsor** [comment]
> @kawsor so it worked in that way?

Right, but the color-most word is not the real one.

**Comment by rookiexiao123** [comment]
![图片](https://user-images.githubusercontent.com/32377884/70306216-34714200-1841-11ea-8cd4-42b332ed52bc.png)
```
    word_least = []     # 3rd place for actual color
    word_middle = []    # 2nd place for actual color
    word_most = []      # 1st place for actual color
    compact_least = []  # 3rd place for shace/class
    compact_middle = [] # 2nd place for shace/class
    compact_most = []   # 1st place for shace/class
    for img in colors.index:
        #sort according to amount of color
        color_word_sorted=[x for _,x in sorted(zip(colors['amount color'][img],colors['color word'][img]))]
        word_least.append(color_word_sorted[0])
        word_middle.append(color_word_sorted[1])
        len1 = len(color_word_sorted)
        if len1 > 2:
            print('color_word_sorted_3')
            print(len1)
            print(color_word_sorted)
            word_most.append(color_word_sorted[2])
        else:
            print('color_word_sorted_2')
            print(color_word_sorted)
            color_word_sorted.insert(2, 'unknown')
            word_most.append(color_word_sorted[2])

        #sort according to amount of color
        color_word_compact_sorted = [x for _,x in sorted(zip(colors['amount color'][img],colors['color word compact'][img]))]
        compact_least.append(color_word_compact_sorted[0])
        compact_middle.append(color_word_compact_sorted[1])
        len2 = len(color_word_compact_sorted)
        if len2 > 2:
            print('color_word_compact_sorted_3')
            print(len2)
            print(color_word_compact_sorted)
            compact_most.append(color_word_compact_sorted[2])
        else:
            print('color_word_compact_sorted_2')
            print(color_word_compact_sorted)
            color_word_compact_sorted.insert(2, 'unknown')
            compact_most.append(color_word_compact_sorted[2])

    colors.drop(colors.columns[[2,3]], axis=1, inplace= True )
```

is it ok?
